In [5]:
#NUMPY
l=[[1,1],[2,2],[3,3],[4,4]]
import numpy as np
np_arr=np.array(l)
np_arr


array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [7]:
type(l),type(np_arr)

(list, numpy.ndarray)

In [15]:
list_1=[1,2,3,4]
list_2=[2,2,3244,4]
list_3=[8,9,6,2]
merge=np.array([list_1,list_2,list_3])
merge


array([[   1,    2,    3,    4],
       [   2,    2, 3244,    4],
       [   8,    9,    6,    2]])

In [11]:
merge.shape

(3, 4)

In [16]:
merge[1][2]

3244

In [20]:
#np ones
np.ones((2,4),dtype=int)


array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
#np zeros
np.zeros((2,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [25]:
n=np.arange(10,20)
n.reshape(2,5)


array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
a=int((input('enter a integer number:')))
print(a)


enter a integer number: 3


3
